### ISSUE TITLE
DateGsonConverter doesn't implement default JSON date format

### ISSUE THREAD

**Issue by jayrmotta** [caelum/vraptor4#931]
The official JSON library both serializes and deserializes from a different variation (which is a shame to exist) of ISO 8601.

The default format is something like yyyy-MM-dd'T'HH:mm:ss.SSS'Z' (by default serializes and deserializes from UTC) instead of yyyy-MM-dd'T'HH:mm:ssZ.

I'm not sure why @Turini added this format in [DateGsonConverter](https://github.com/caelum/vraptor4/blob/60ffcb9d3d48d6a7a51e945c07a69e17e507229d/vraptor-core/src/main/java/br/com/caelum/vraptor/serialization/gson/DateGsonConverter.java) but all JavaScript libraries will use JSON parse and stringify.

Here are a couple links I've researched to get to this conclusion:
- http://stackoverflow.com/questions/10286204/the-right-json-date-format
- http://stackoverflow.com/questions/16204231/getting-iso8601-from-jodatime-with-milliseconds
- http://weblog.west-wind.com/posts/2014/Jan/06/JavaScript-JSON-Date-Parsing-and-real-Dates

I was thinking to fork vraptor4 fix it and pull request the solution, but I wonder how that can be achieved without breaking every single person that already uses vraptor4, which also made me think how these folk coped with that problem.

**Comment by jayrmotta** [comment]
Ohh.. I just got curious how vraptor 3 used to work and now these problems are happening in vraptor 4 and look what I've found (https://github.com/caelum/vraptor/blob/master/vraptor-core/src/main/java/br/com/caelum/vraptor/util/ISO8601Util.java), it uses the format I've mentioned above except the "Z" is used as a variable instead of a constant (wrapped in single quotes).

**Comment by Turini** [comment]
@jayrmotta, please [take a look at my old PR](https://github.com/caelum/vraptor4/pull/562#discussion_r13115519). Initially I've used `'Z'`, but @lucascs and 
@garcia-jj agreed that I shouldn't use 'Z', because `+03:00` was also valid ISO. It's not?

**Comment by garcia-jj** [comment]
Z literal is an abreviation to Zulu time, means UTC. To use the literal Zulu in the code we need to convert the date from current timezone to UTC. 

`2015-01-01'T'05:00:00.000+03:00` isn't the same as `2015-01-01'T'05:00:00.000'Z'`, but is `2015-01-01'T'08:00:00.000'Z'`.

The a look in this section from IETF specs about ISO8601: http://tools.ietf.org/html/rfc3339#section-4.3

> If the time in UTC is known, but the offset to local time is unknown,
   this **can be represented with an offset of "-00:00"**.  This differs
   semantically from an offset of "Z" or "+00:00", which imply that UTC
   is the preferred reference point for the specified time.  RFC2822
   [IMAIL-UPDATE] describes a similar convention for email.

Reading this section I understand that serializing as Zulu time is not mandatory. If the application dates are specified in another timezones, applications are free to use properly timezones without calculate the time in Zulu time.

IMHO, the component writed by @Turini is working as expected. The code you linked from vraptor 3 was writed by @dipold and uses fixed Zulu literal because in versions prior to Java 7 was not printing the timezone properly, so the only way was using fixed Zulu literal.

**Comment by jayrmotta** [comment]
It is such an honor for me to debate this with you guys, thanks for that!

I can't argue against the the correctness of the actual implementation, you both are correct! However, I'd like to ask you guys to consider what I'm saying because it is the web default, I'm not sure about all other serializers and deserializers to integrate backend or mobile applications, but in web applications using JSON there is this huge setback and I believe you wouldn't like to ignore it.

Therefore, we could think an implementation that supports both what is being supported today and what was supported in VRaptor3. I've seen other REST/MVC technologies with great, robust and flexible date support and VRaptor is a mainstream technology that shouldn't be the one not supporting web default formats.

Does that sounds reasonable?

**Comment by garcia-jj** [comment]
Are you getting an error when serialize, deserialize, or your goal is only to standardize the component?

If your answer is the 2nd option, I think we can test if we found the literal `Zulu`, and use a alternative pattern. Or if your anwer is the 1st or last options, extracting the pattern to a method will help you because allow you to specializes the class to use another pattern.

And feel free to ask us for any technical questions you want. Any discussion will increase our knowledge.

**Comment by jayrmotta** [comment]
@garcia-jj Deserializing a date serialized by JSON (javascript lib) in VRaptor is what led me here. However I'm also having trouble deserializing the date serialized by VRaptor because JSON uses the same format to deserialize.

Maybe this format should be customized in properties, but I'm sure adding this second format compatible with JSON default date format will give the framework and it's users a great improvement.

**Comment by Turini** [comment]
adding a second format will make it unnecessarily slower (especially when there are 
a lot of date conversions on the request). IMO extracting the pattern to a method just 
like @garcia-jj suggested would be enought. What do you think @jayrmotta, `@all`?

**Comment by jayrmotta** [comment]
That sounds nice, maybe a property that could override the default behavior.

**Comment by Turini** [comment]
Great! What do you think about extracting a method like in the sample:

```java
@Dependent
public class DateGsonConverter 
	implements JsonDeserializer<Date>, JsonSerializer<Date> {

	private final SimpleDateFormat iso8601Format;

	public DateGsonConverter() {
		this.iso8601Format = new SimpleDateFormat(getPattern());
	}
	// ...
	public String getPattern() { return "yyyy-MM-dd'T'HH:mm:ssZ" }
}
```

With this change, users could change it's pattern just like this:

```java
@Specializes
public class CustomDateGsonConverter extends DateGsonConverter {
	@Override
	public String getPattern() { return //any custom pattern }
}
```

This extractegy goes closer to the way we do customize stuff in VRaptor 4.
What do you think? Do you want to send us a pull request with this change?
