### ISSUE TITLE
One minute example: upload

### ISSUE THREAD

**Issue by dobau** [caelum/vraptor4#994]
The example "One minute example: upload" doesn't work for release 4.1.4 (current vraptor release).

Method writeTo is unavailable.

```java
public void atualizaFoto(Perfil perfil, UploadedFile foto) {
    File fotoSalva = new File("/path/to/file/repository", foto.getFileName());
    foto.writeTo(fotoSalva);
    dao.atribui(fotoSalva, perfil);
}
```

Link: http://www.vraptor.org/en/docs/download-and-upload/

**Comment by renanigt** [comment]
Taking a look at #883, it's targeted to 4.2, currently vraptor version is 4.2.0-RC2. :smiley:

**Comment by garcia-jj** [comment]
Yep. This occurs because we can't versioning published docs at this time.

**Comment by Turini** [comment]
@dobau 4.2 will be released very soon!

**Comment by dobau** [comment]
That issue made me rethink about some questions...

1 - Do you recommend to use the candidate version, same in production?
2 - Do we can to version the documentation? Because have things works in a version but not in other, "One minute example" is a exemple.
3 - Becasuse the version 4.1.4 is final so I decides use it. Theoretically it's more stable than one candidate, and it is usually what happens with other frameworks as hibernate.

---
(PT)

Essa issue me fez repensar algumas questões...

1 - Vocês recomendam utilizar a versão candidate, mesmo em produção?
2 - Não podemos versionar a documentação? Tem coisas que funcionam em uma versão e não em outra, o "One minute example" é um exemplo.
3 - Como a versão 4.1.4 é a final decidi utilizá-la, pois teoricamente é mais estável que uma candidate, geralmente é o que acontece com outros frameworks, correto?

**Comment by garcia-jj** [comment]
1) I have a large app that runs a customized version of vraptor based on master branch: https://github.com/garcia-jj/vraptor4/commits/ot-julia-2.1. And I have no problems. The idea is using untested features in this app to use in my contributions to vraptor team. If you feel free to test some unstable feature, you can use without any problem. But if you prefer to use stable versions, don't use RC.

2) In the past, when I contributed to docs, I used texts like 'If you are using version 4.1.2 you can enable blah blah blah'. Or something like this. Versioning docs are not too easy as I know.

3) Like the 2st question. I love to use unreleased versions in my personal project, because is an opportunity  to get bugs to contribute to the projects I use.

**Comment by dobau** [comment]
About the first question *I* agree with your point of view @garcia-jj, but try to convince a project owner of that.

About the another is OK too.

For me that question is answered :smile:

**Comment by garcia-jj** [comment]
Thank you.
